apiVersion: v1
kind: Service
metadata:
  name: position-tracker-service
spec:
  type: ClusterIP
  selector:
    app: position-tracker
  ports:
    - name: ws
      port: 8080
      targetPort: 8080
    - name: api
      port: 9001
      targetPort: 9001
